---
name: BlazinFly1
main: iiFlamiinBlaze\BlazinFly\BlazinFly
description: An advanced survival fly plugin!
version: 1.8.6
api:
- 3.0.0
author: iiFlamiinBlaze
commands:
  fly1:
    description: Command which allows flight when in Survival Mode!
permissions:
  fly1.command:
    description: BlazinFly command permission
    default: op
...
