---
#   _____                    _   _           _
#  /  ___|                  | | | |         | |
#  \ `--.  ___ ___  _ __ ___| |_| |_   _  __| |
#   `--. \/ __/ _ \| '__/ _ \  _  | | | |/ _` |
#  /\__/ / (_| (_) | | |  __/ | | | |_| | (_| |
#  \____/ \___\___/|_|  \___\_| |_/\__,_|\__,_|
#
# ScoreHud, a Scoreboard plugin for PocketMine-MP
# Copyright (c) 2018 JackMD  < https://github.com/JackMD >
#
# Discord: JackMD#3717
# Twitter: JackMTaylor_
#
# This software is distributed under "GNU General Public License v3.0".
# This license allows you to use it and/or modify it but you are not at
# all allowed to sell this plugin at any cost. If found doing so the
# necessary action required would be taken.
#
# ScoreHud is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License v3.0 for more details.
#
# You should have received a copy of the GNU General Public License v3.0
# along with this program. If not, see
# <https://opensource.org/licenses/GPL-3.0>.
#  -----------------------------------------------------------------------

# DO NOT EDIT THIS VALUE.
# ONLY FOR INTERNAL USE.
config-version: "TaylorSwift"

# The amount in seconds after which the Scoreboard would update.
# Increase this value if your server seems to lag.
# Default: 3 seconds.
update-interval: 1

# Changing titles of the scoreboard.
# Can be of any number.
server-names:
- "§l§eＡ§6Ｕ§aＲＡ ＫＩＮＧＤＯＭ"
- "§l§6Ａ§eＵ§6Ｒ§aＡ ＫＩＮＧＤＯＭ"
- "§l§aＡ§6Ｕ§eＲ§6Ａ§a ＫＩＮＧＤＯＭ"
- "§l§aＡＵ§6Ｒ§eＡ§6 Ｋ§aＩＮＧＤＯＭ"
- "§l§aＡＵＲ§6Ａ§e Ｋ§6Ｉ§aＮＧＤＯＭ"
- "§l§aＡＵＲＡ§6 Ｋ§eＩ§6Ｎ§aＧＤＯＭ"
- "§l§aＡＵＲＡ Ｋ§6Ｉ§eＮ§6Ｇ§aＤＯＭ"
- "§l§aＡＵＲＡ ＫＩ§6Ｎ§eＧ§6Ｄ§aＯＭ"
- "§l§aＡＵＲＡ ＫＩＮ§6Ｇ§eＤ§6Ｏ§aＭ"
- "§l§aＡＵＲＡ ＫＩＮＧ§6Ｄ§eＯ§6Ｍ"
- "§l§aＡＵＲＡ ＫＩＮＧＤ§6Ｏ§eＭ"
- "§l§aＡＵＲＡ ＫＩＮＧＤＯ§6Ｍ"
- "§l§eＡＵＲＡ §6ＫＩＮＧＤＯＭ"
# Currently Supported Tags:
# {name}                - Name of the player.
# {money}               - Money of the player. (Requires EconomyAPI).
# {online}              - The number of online players.
# {max_online}          - Max number of players allowed on the server.
# {rank}                - Players current in-game rank/group. (Requires PurePerms).
# {prison_rank}         - Get players Prison rank. (Requires RankUp)
# {item_name}           - Name of the item in players hand.
# {item_id}             - ID of the item in players hand.
# {item_meta}           - Meta/Damage of the item in players hand.
# {item_count}          - Amount of item in the players hand.
# {x}/{y}/{z}           - X/Y/Z coordinate of the player.
# {faction}             - Faction of the player. (Requires FactionsPro).
# {load}                - Current load on the server (0 - 100%)
# {tps}                 - TPS of the server.
# {level_name}          - Name of the players current level/world.
# {level_folder_name}   - Folder name of the players current level/world.
# {ip}                  - IP of the player.
# {ping}                - Ping of the player.
# {kills}               - Get kill count of a player. (Requires KDR)
# {deaths}              - Get death count of a player. (Requires KDR)
# {kdr}                 - Get kill to death ratio of a player. (Requires KDR)

# Add the lines that would be shown on the Scoreboard.
# Follow the same pattern as below.
# You can edit the lines already set below and adjust them according to your needs.
# NOTE: You can only set a maximum of 15 lines and no more.
score-lines:

- "§6✈§a Xin Chào:§b {name}"
- "§6✈§a Yên:§b {money}"
- "§6✈§a Point:§b {point}"
- "§6✈§a Guild:§b {faction}"
- "§6✈§a PING:§b {ping}"
- "§6✈§a Giờ:§b {time}"
- "§6✈§a Ngày:§b {day}"
- "§l§a♣ §cVOTE:§6 bit.do/akd-vote"
- "§l§a♣ §cIP:§6 Play.AuraKingDom.tk"

...