---
first_join: '[DailyReward] Hello, you are the first day on the server.'
daily_join: '[DailyReward] Hello, you play on the server already {count} day in a
  row.'
' daily_join ': ' [DailyReward] Hello, you have been playing {count} day in a row
  on the server.'
...
