#,-.----.
#\    /  \                                           ,----..      ,---,.  .--.--.     ,---,
#|   :    \   ,--,                                  /   /   \   ,'  .' | /  /    '. ,--.' |              ,-.----.
#|   |  .\ :,--.'|                                 |   :     :,---.'   ||  :  /`. / |  |  :       ,---.  \    /  \
#.   :  |: ||  |,     ,----._,.  ,----._,.         .   |  ;. /|   |   .';  |  |--`  :  :  :      '   ,'\ |   :    |
#|   |   \ :`--'_    /   /  ' / /   /  ' /     .--,.   ; /--` :   :  |-,|  :  ;_    :  |  |,--. /   /   ||   | .\ :
#|   : .   /,' ,'|  |   :     ||   :     |   /_ ./|;   | ;    :   |  ;/| \  \    `. |  :  '   |.   ; ,. :.   : |: |
#;   | |`-' '  | |  |   | .\  .|   | .\  ., ' , ' :|   : |    |   :   .'  `----.   \|  |   /' :'   | |: :|   |  \ :
#|   | ;    |  | :  .   ; ';  |.   ; ';  /___/ \: |.   | '___ |   |  |-,  __ \  \  |'  :  | | |'   | .; :|   : .  |
#:   ' |    '  : |__'   .   . |'   .   . |.  \  ' |'   ; : .'|'   :  ;/| /  /`--'  /|  |  ' | :|   :    |:     |`-'
#:   : :    |  | '.'|`---`-'| | `---`-'| | \  ;   :'   | '/  :|   |    \'--'.     / |  :  :_:,' \   \  / :   : :
#|   | :    ;  :    ;.'__/\_: | .'__/\_: |  \  \  ;|   :    / |   :   .'  `--'---'  |  | ,'      `----'  |   | :
#`---'.|    |  ,   / |   :    : |   :    :   :  \  \\   \ .'  |   | ,'              `--''                `---'.|
#  `---`     ---`-'   \   \  /   \   \  /     \  ' ; `---`    `----'                                       `---`
#                      `--`-'     `--`-'       `--`

double-tap: true
shop-type: sign