name: BuyEnchant
main: buyec\Main
version: 1.0
api: 3.0.0
commands:
  buyec:
    description: mua enchant 5 lv (gia 20000xu/1 cấp)
  tokenenchant:
    description: mua enchant
  listec:
    description: danh sach enchantment